name: Update TigerTag JSON

on:
  schedule:
    # Runs every 2 hours at minute 0 (e.g. 00:00, 02:00, 04:00, …)
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run JSON Generation Script
        run: node scripts/update-db.js

      - name: Commit and Push JSON Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          # Use XSPOOL_PAT instead of the default GITHUB_TOKEN
          git remote set-url origin https://x-access-token:${{ secrets.XSPOOL_PAT }}@github.com/xperiments/xspool-bin.git
          git add -f ./db/tigerTagDatabase.json
          git commit -m "chore: update TigerTag JSON [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          XSPOOL_PAT: ${{ secrets.XSPOOL_PAT }}
